package com.biprom.DentalArno.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Accordion;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements com.biprom.DentalArno.View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LightDesign extends VerticalLayout {
    protected Accordion lightAccordion;

    public LightDesign() {
        Design.read(this);
    }
}
