package com.biprom.DentalArno.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements com.biprom.DentalArno.View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends HorizontalLayout {
    protected Button menuButton;
    protected CssLayout menu;
    protected Button bVerlichting;
    protected Button bScreens;
    protected Button bVideofoon;
    protected Button bWeather;
    protected Label viewTitle;
    protected CssLayout content;
    protected Panel subPanel;

    public MainDesign() {
        Design.read(this);
    }
}
