package com.biprom.DentalArno.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements com.biprom.DentalArno.View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class WoonkamerVerlichting extends VerticalLayout {
    protected Button buttonWoonkamer;
    protected Button buttonTv;
    protected Button buttonLeeshoek;

    public WoonkamerVerlichting() {
        Design.read(this);
    }
}
